version: '3'
services:
  app:
    build: ./app
    container_name: app
    ports:
      - '80:3000'
      - '443:443'
    restart: always
    volumes:
      - certbot-webroot-fourwardutils:/app/public/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

  certbot:
    build: ./certbot
    container_name: certbot
    restart: always
    volumes:
      - certbot-webroot-fourwardutils:/webroots/fourwardutils.tk/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

volumes:
  certbot-webroot-fourwardutils:
  certbot-letsencrypt: